"""Website ops reporting and automation helpers."""

from .core import (
    DEFAULT_CONFIG_PATH,
    DEFAULT_WEBSITE_OPS_ROOT,
    WebsiteOpsConfig,
    build_daily_report,
    collect_page_observation,
    collect_page_observations,
    detect_page_issues,
    inspect_html_document,
    load_config,
    load_feedback_entries,
    parse_html_document,
    render_daily_report_html,
    render_daily_report_markdown,
    run_daily_report_pipeline,
    save_feedback_entry,
    update_feedback_entry,
    write_daily_report_artifacts,
)
from .executor import (
    ExecutionError,
    execute_approved_feedback,
    execute_feedback_action,
    execution_enabled,
)

__all__ = [
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_WEBSITE_OPS_ROOT",
    "WebsiteOpsConfig",
    "build_daily_report",
    "collect_page_observation",
    "collect_page_observations",
    "detect_page_issues",
    "inspect_html_document",
    "load_config",
    "load_feedback_entries",
    "parse_html_document",
    "render_daily_report_html",
    "render_daily_report_markdown",
    "run_daily_report_pipeline",
    "save_feedback_entry",
    "update_feedback_entry",
    "write_daily_report_artifacts",
    "ExecutionError",
    "execute_approved_feedback",
    "execute_feedback_action",
    "execution_enabled",
]
